name: 'Node.js Pre-Build'
description: 'Setup Node.js environment and install dependencies'

inputs:
  node_version:
    description: 'Node.js version to use'
    required: false
    default: '20'
  working_directory:
    description: 'Working directory containing package.json'
    required: false
    default: '.'
  enable_caching:
    description: 'Enable npm caching'
    required: false
    default: 'true'
  package_manager:
    description: 'Package manager to use (npm, yarn, pnpm)'
    required: false
    default: 'npm'
  install_command:
    description: 'Custom install command (overrides package_manager)'
    required: false
    default: ''
  run_install:
    description: 'Run package manager install'
    required: false
    default: 'true'

outputs:
  node_version:
    description: 'The Node.js version that was installed'
    value: ${{ steps.setup.outputs.node-version }}
  cache_hit:
    description: 'Whether the npm cache was hit'
    value: ${{ steps.setup.outputs.cache-hit }}

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      id: setup
      uses: actions/setup-node@v6
      with:
        node-version: ${{ inputs.node_version }}
        cache: ${{ inputs.enable_caching == 'true' && inputs.package_manager || '' }}
        cache-dependency-path: ${{ inputs.working_directory }}/package-lock.json

    - name: Install Dependencies (npm ci)
      if: inputs.run_install == 'true' && inputs.install_command == '' && inputs.package_manager == 'npm'
      working-directory: ${{ inputs.working_directory }}
      run: npm ci
      shell: bash

    - name: Install Dependencies (yarn)
      if: inputs.run_install == 'true' && inputs.install_command == '' && inputs.package_manager == 'yarn'
      working-directory: ${{ inputs.working_directory }}
      run: yarn install --frozen-lockfile
      shell: bash

    - name: Install Dependencies (pnpm)
      if: inputs.run_install == 'true' && inputs.install_command == '' && inputs.package_manager == 'pnpm'
      working-directory: ${{ inputs.working_directory }}
      run: pnpm install --frozen-lockfile
      shell: bash

    - name: Install Dependencies (custom)
      if: inputs.run_install == 'true' && inputs.install_command != ''
      working-directory: ${{ inputs.working_directory }}
      run: ${{ inputs.install_command }}
      shell: bash
