name: 'GCP Authentication and Docker Login'
description: 'Authenticate to Google Cloud using Workload Identity and login to Docker registry'

inputs:
  workload_identity_provider:
    description: 'The workload identity provider for GCP authentication'
    required: true
  service_account:
    description: 'The service account email for GCP authentication'
    required: true
  docker_registry:
    description: 'Docker registry hostname'
    required: true
    default: 'europe-west2-docker.pkg.dev'
  docker_username:
    description: 'Docker registry username'
    required: false
    default: 'oauth2accesstoken'

outputs:
  access_token:
    description: 'The GCP access token'
    value: ${{ steps.auth.outputs.access_token }}

runs:
  using: 'composite'
  steps:
    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v3
      with:
        token_format: access_token
        workload_identity_provider: ${{ inputs.workload_identity_provider }}
        service_account: ${{ inputs.service_account }}

    - name: Docker Login
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.docker_registry }}
        username: ${{ inputs.docker_username }}
        password: ${{ steps.auth.outputs.access_token }}
      shell: bash
