name: 'Docker Multi-Platform Build and Push'
description: 'Build and push Docker images for multiple platforms using Buildx'

inputs:
  context:
    description: 'Build context path'
    required: false
    default: '.'
  dockerfile:
    description: 'Path to Dockerfile'
    required: false
    default: 'Dockerfile'
  push:
    description: 'Push the image to registry'
    required: false
    default: 'true'
  tags:
    description: 'List of tags (comma or newline separated)'
    required: true
  platforms:
    description: 'Target platforms for build'
    required: false
    default: 'linux/amd64,linux/arm64'
  build_args:
    description: 'List of build-time variables (newline separated)'
    required: false
    default: ''
  cache_from:
    description: 'External cache sources'
    required: false
    default: ''
  cache_to:
    description: 'Cache export destinations'
    required: false
    default: ''
  target:
    description: 'Target build stage'
    required: false
    default: ''

outputs:
  image_id:
    description: 'Image ID'
    value: ${{ steps.build.outputs.imageid }}
  digest:
    description: 'Image digest'
    value: ${{ steps.build.outputs.digest }}
  metadata:
    description: 'Build result metadata'
    value: ${{ steps.build.outputs.metadata }}

runs:
  using: 'composite'
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      shell: bash

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      shell: bash

    - name: Build and push
      id: build
      uses: docker/build-push-action@v6
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        push: ${{ inputs.push }}
        tags: ${{ inputs.tags }}
        platforms: ${{ inputs.platforms }}
        build-args: ${{ inputs.build_args }}
        cache-from: ${{ inputs.cache_from }}
        cache-to: ${{ inputs.cache_to }}
        target: ${{ inputs.target }}
      shell: bash
